# Generated by Django 3.2.6 on 2021-12-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appli_no', models.CharField(max_length=90)),
                ('vac_no', models.CharField(max_length=90)),
                ('applicant_name', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('date_of_birth', models.CharField(max_length=90)),
                ('age', models.CharField(max_length=90)),
                ('gender', models.CharField(max_length=90)),
                ('mail', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('qualification', models.CharField(max_length=90)),
                ('experience', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_application',
            },
        ),
        migrations.CreateModel(
            name='tbl_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=90)),
                ('category', models.CharField(max_length=90)),
                ('name', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_client',
            },
        ),
        migrations.CreateModel(
            name='tbl_client_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=90)),
                ('jobmaster_id', models.CharField(max_length=90)),
                ('service_name', models.CharField(max_length=90)),
                ('client_id', models.CharField(max_length=90)),
                ('no_of_employees', models.CharField(max_length=90)),
                ('request_date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_client_request',
            },
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(max_length=90)),
                ('employee_id', models.CharField(max_length=90)),
                ('complaint', models.CharField(max_length=90)),
                ('complaint_date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_complaint',
            },
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(max_length=90)),
                ('feedback', models.CharField(max_length=90)),
                ('client_id', models.CharField(max_length=90)),
                ('date', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_feedback',
            },
        ),
        migrations.CreateModel(
            name='tbl_interview_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_id', models.CharField(max_length=90)),
                ('vacancy_no', models.CharField(max_length=90)),
                ('application_no', models.CharField(max_length=90)),
                ('interview_date', models.CharField(max_length=90)),
                ('time', models.CharField(max_length=90)),
                ('venue', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_interview_list',
            },
        ),
        migrations.CreateModel(
            name='tbl_job_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=90)),
                ('job_name', models.CharField(max_length=90)),
                ('qualification', models.CharField(max_length=90)),
                ('experience', models.CharField(max_length=90)),
                ('basic_sal', models.CharField(max_length=90)),
                ('ta', models.CharField(max_length=90)),
                ('da', models.CharField(max_length=90)),
                ('hra', models.CharField(max_length=90)),
                ('lic', models.CharField(max_length=90)),
                ('pf', models.CharField(max_length=90)),
                ('loan_limit', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_job_master',
            },
        ),
        migrations.CreateModel(
            name='tbl_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_id', models.CharField(max_length=90)),
                ('employee_id', models.CharField(max_length=90)),
                ('job_id', models.CharField(max_length=90)),
                ('leave_date', models.CharField(max_length=90)),
                ('no_of_days', models.CharField(max_length=90)),
                ('application_date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_leave',
            },
        ),
        migrations.CreateModel(
            name='tbl_loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=90)),
                ('employee_id', models.CharField(max_length=90)),
                ('loan_amount', models.CharField(max_length=90)),
                ('recovery_amount', models.CharField(max_length=90)),
                ('loan_application_date', models.CharField(max_length=90)),
                ('loan_sanction_date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_loan',
            },
        ),
        migrations.CreateModel(
            name='tbl_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('category', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_login',
            },
        ),
        migrations.CreateModel(
            name='tbl_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_no', models.CharField(max_length=90)),
                ('job_id', models.CharField(max_length=90)),
                ('name', models.CharField(max_length=90)),
                ('no_of_vac', models.CharField(max_length=90)),
                ('age_limit', models.CharField(max_length=90)),
                ('appli_last_date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_vacancy',
            },
        ),
    ]
