# Generated by Django 3.2.6 on 2021-12-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g4security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_selection_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_id', models.CharField(max_length=90)),
                ('interview_id', models.CharField(max_length=90)),
                ('applicant_name', models.CharField(max_length=90)),
                ('remark', models.CharField(max_length=90)),
                ('reporting_date', models.CharField(max_length=90)),
                ('time', models.CharField(max_length=90)),
                ('reporting_office', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_selection_list',
            },
        ),
    ]
