# Generated by Django 3.2.6 on 2022-01-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g4security', '0003_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_client_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_employee_id', models.CharField(max_length=90)),
                ('client_id', models.CharField(max_length=90)),
                ('emp_id', models.CharField(max_length=90)),
                ('request_id', models.CharField(max_length=90)),
                ('allotment_date', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'tbl_client_employee',
            },
        ),
    ]
