# Generated by Django 4.0 on 2022-03-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g4security', '0004_tbl_client_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_employee',
            old_name='job_id',
            new_name='vacancyname',
        ),
    ]
