# Generated by Django 4.0 on 2022-03-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g4security', '0005_rename_job_id_tbl_employee_vacancyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_salary_statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_id', models.CharField(max_length=90)),
                ('month', models.CharField(max_length=90)),
                ('year', models.CharField(max_length=90)),
                ('employee_id', models.CharField(max_length=90)),
                ('basic_salary', models.IntegerField()),
                ('grows_pay', models.IntegerField()),
                ('deduction', models.IntegerField()),
                ('netamount', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_salary_statement',
            },
        ),
        migrations.AlterField(
            model_name='tbl_job_master',
            name='basic_sal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_job_master',
            name='da',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_job_master',
            name='hra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_job_master',
            name='lic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_job_master',
            name='pf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_job_master',
            name='ta',
            field=models.IntegerField(),
        ),
    ]
