# Generated by Django 4.0 on 2022-03-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g4security', '0006_tbl_salary_statement_alter_tbl_job_master_basic_sal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_employee',
            name='status',
            field=models.CharField(default='active', max_length=90),
            preserve_default=False,
        ),
    ]
