# Generated by Django 3.2.11 on 2022-04-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g4security', '0008_tbl_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_client',
            name='id_proof',
            field=models.CharField(default='jj', max_length=90),
            preserve_default=False,
        ),
    ]
